yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('tech/', views.Tech.as_view(), name='tech'),
    path('author/', views.Author.as_view(), name='author'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.create_post, name='create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/',
         views.index_follow,
         name='index_follow'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/registration/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/registration/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('auth/', include(('users.urls', 'users'), namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include(('about.urls', 'about'), namespace='about')),
    path('admin/', admin.site.urls),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/description.html
{% load thumbnail %}
    <ul class="posts__data posts__ul">
        <li>
            Автор: <a href="{% url 'posts:profile' post.author %}" class="posts_author"> {{ post.author.get_full_name }} <span>@aka</span> {{post.author}}</a>
        </li>
        <li class="posts__li">
          <span class="post_article">Дата публикации:</span> {{ post.created|date:"d E Y" }}
        </li>
    </ul>
    {% thumbnail post.image "900x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p class="posts__text">{{ post.text|linebreaksbr }}</p>

yatube/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">© {{year}} Copyright 
      <p><span style="color:red">Ya</span>tube</p> 
    </div>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<header id="header">
    <div class="header__container">   
      <nav class=" header__nav navbar  navbar-light" >
          <a class="navbar-brand header__link " href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo2.png' %}" class="header_icon" >
            <p class="header__logo">
              <span>Ya</span>tube
            </p>
          </a>
          <div class="nav__wrapper">
            <a href="{% url 'about:author' %}" class='nav__text'>Об авторе</a>
            <a href="{% url 'about:tech' %}" class="nav__text">️ Технологии</a>
            {% if user.is_authenticated %}
            <a class="nav__text" href="{% url 'posts:create' %}">
              ️ Новая запись
            </a>
           
            <a href="{% url 'posts:profile' user.username %}" class="nav__text">
               Пользователь: <span>{{ user.username }}</span>
            </a>
            <a class="" href="{% url 'users:logout' %}" class="nav__text">
               Выйти
            </a>
          {% else %}
            <a class="" href="{% url 'users:login' %}">
               Войти
            </a>
            <a class="" href="{% url 'users:signup' %}">
              ️ Регистрация
            </a>
          {% endif %}
          </div>
          
          <div class="header__btn header__link ">
            <img src="{% static 'img/free-icon-menu-561184.png' %}" class=" header__list-btn">
      </div>
        
      </nav> 
    </div>
    
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="my-5 post__link">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              Предыдущая
            </a>
          </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }}</span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              Следующая
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
              Последняя
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
{% endif %}