yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('tech/', views.Tech.as_view(), name='tech'),
    path('author/', views.Author.as_view(), name='author'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.create_post, name='create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/',
         views.index_follow,
         name='index_follow'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('auth/', include(('users.urls', 'users'), namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include(('about.urls', 'about'), namespace='about')),
    path('admin/', admin.site.urls),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
    )
    slug = models.SlugField(
        unique=True,
        max_length=20,
        verbose_name='URL адреса группы'
    )
    description = models.TextField(
        verbose_name='Описание группы',
    )

    def __str__(self):
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        verbose_name='Текст вашего поста'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='select',
        help_text='Выберите группу или оставьте пустым',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='image',
    )

    @property
    def amount_author_post(self):
        return self.author.posts.all().count()

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        blank=False,
        null=False,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        blank=False,
        null=False,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField()

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'comments'

    def __str__(self):
        comment_text = self.text[:20]
        return f'Комментарий {comment_text}'

    @property
    def author_comment(self):
        return self.author.username


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

yatube/posts/forms.py
from .models import Post, Comment

from django.forms import ModelForm


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image', )


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = (
            'text',
        )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .utilits import get_page
from .forms import PostForm, CommentForm
from .models import Group, User, Post, Follow


def index(request):
    posts = Post.objects.all().select_related('author', 'group')
    page_obj = get_page(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.all()
    page_obj = get_page(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = get_page(request, posts)
    following = False
    if request.user.is_authenticated and request.user != author:
        following = Follow.objects.filter(
            author=author,
            user=request.user
        ).exists()
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    post_amount = post.amount_author_post
    context = {
        'post': post,
        'form': form,
        'post_amount': post_amount,
        'comments': comments
    }
    return render(request, 'posts/post_details.html', context)


@login_required
def create_post(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", username=post.author)
    context = {
        "form": form,
        'is_edit': False
    }
    return render(request, "posts/create_post.html", context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.user != post.author:
        return redirect("posts:post_detail", post_id)
    if form .is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)
    context = {
        'form': form,
        'is_edit': True
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def index_follow(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = get_page(request, posts)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user.is_authenticated and request.user != author:
        if not Follow.objects.filter(
            author=author,
            user=request.user
        ).exists():
            Follow.objects.create(user=request.user,
                                  author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(user=request.user, author=author)
    if follow.exists():
        follow.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
    {% extends "base.html" %}
    {% load static %}
    {% block header %}{% endblock %}
    {% block title %}
      {% if is_edit %}
         Yatube | редактор
      {% else %}
      Yatube | новый пост
      {% endif %}
    {% endblock %}
    {% block content %}
        <section id="form">
          <form method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row form__wrapper">
                {% for field in form %}
                  <div class="form-group  " >
                    <label for="{{ field.id_for_label }}" class="col-md-4  form__label">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required">*</span>
                      {% endif %}
                      {% if form.errors %}
                      <div class="alert alert-danger" role="alert">
                        Неизвестная Ошибка
                      </div>
                    {% endif %}
                    </label>
                    <div class="col-md-6 form__select {{ field.help_text }}">
                      {{ field }}

                    </div>
                  </div>
                {% endfor %}
            </div>
            <div class="">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                   Изменить
                {% else %}
                   Сохранить
                {% endif %}
              </button>
            </div>

          </form>
        </section>
    {% endblock %} 
  

yatube/templates/posts/follow.html
{% extends "base.html" %}

{% block title %}
    Yatube
{% endblock %}

{% block content %}

            <section id="posts">
      <h1 class="main__header">Подписки</h1>

      <div class="posts container py-5">
          {% if user.is_authenticated %}
              <div class="row my-3">
                <ul class="nav nav-tabs">
                  <li class="nav-item">
                    <a
                      class="nav-link {% if index %}active{% endif %} posts__menu"
                      href="{% url 'posts:index' %}"
                    >
                      Все авторы
                    </a>
                  </li>
                  <li class="nav-item">
                    <a
                       class="nav-link {% if follow %}active{% endif %} posts__menu"
                       href="{% url 'posts:index_follow' %}"
                    >
                      Избранные авторы
                    </a>
                  </li>
                </ul>
              </div>
              {% else %}
              <h2 class="posts__header">Новые публикации</h2>
        {% endif %}
          {% for post in page_obj %}
            <div class="posts_container">
              {% include 'includes/description.html' %}
                <div class="post__description">
                  {% if post.group %}
                  <div class="post__link">
                    <a href="{% url 'posts:group_list' post.group.slug %}" class="posts__data">все записи группы: {{post.group.slug}}</a>
                  </div>
                  {% endif %}
                    {% if post.author == user %}
                        <div class="post__link">
                          <a href="{% url 'posts:edit' post.id %}" class="posts__data"> Pедактировать пост </a>
                        </div>
                    {% endif %}
                        <div class="post__link">
                          <a href="{% url "posts:post_detail" post.id %}" class="posts__data"> О посте </a>
                        </div>
                </div>
            </div>



              {% if forloop.last %}

              {% endif %}

          {% endfor %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %}
    Yatube | {{group.title}}
{% endblock %}
{% block content %}
  {% if page_obj %}
    <section id="posts">
      <h1 class="main__header">Все посты группы: {{ group.title }}</h1> 
      <div class="posts container py-5">
         <p> {{ group.description }} </p>
          {% for post in page_obj %}
            <div class="posts_container">
              {% include 'includes/description.html' %}    
            </div> 
            
          {% endfor %}
          {% else %}
            <p class="py-5 nothing">В группе нет постов :( </p>
          {% endif %}
      </div>
    </section>
{% endblock %} 

      

yatube/templates/posts/index.html
{% extends "base.html" %}

{% block title %}
    Yatube 
{% endblock %}

{% block content %}
    {% load cache %}
    {% cache 5 index_page page_obj.number %}
            <section id="posts">
              <h1 class="main__header">Главная страница</h1>

              <div class="posts container py-5">
                  {% if user.is_authenticated %}
                      <div class="row my-3">
                        <ul class="nav nav-tabs">
                          <li class="nav-item">
                            <a
                              class="nav-link {% if index %}active{% endif %} posts__menu"
                              href="{% url 'posts:index' %}"
                            >
                              Все авторы
                            </a>
                          </li>
                          <li class="nav-item">
                            <a
                               class="nav-link {% if follow %}active{% endif %} posts__menu"
                               href="{% url 'posts:index_follow' %}"
                            >
                              Избранные авторы
                            </a>
                          </li>
                        </ul>
                      </div>
                      {% else %}
                      <h2 class="posts__header">Новые публикации</h2>
                {% endif %}
                  {% for post in page_obj %}
                    <div class="posts_container {% if post.author == user %} posts_container-user {% endif %}">
                      {% include 'includes/description.html' %}
                        <div class="post__description">
                          {% if post.group %}
                          <div class="post__link">
                            <a href="{% url 'posts:group_list' post.group.slug %}" class="posts__data">Все записи группы: {{post.group.slug}}</a>
                          </div>
                          {% endif %}
                            {% if post.author == user %}
                                <div class="post__link">
                                  <a href="{% url 'posts:edit' post.id %}" class="posts__data"> Pедактировать пост  </a>
                                </div>
                            {% endif %}
                                <div class="post__link">
                                  <a href="{% url "posts:post_detail" post.id %}" class="posts__data"> О посте </a>
                                </div>
                        </div>
                    </div>



                      {% if forloop.last %}

                      {% endif %}

                  {% endfor %}

    {% endcache %}

{% endblock %}

yatube/templates/posts/post_details.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} Пост | Yatube {% endblock %}
{% block content %}
    <section id="info">
      <div class="row post__info">
        <aside class="col-12 col-md-3 ">
          <ul class="list-group list-group-flush info__blocks">
            <li class="list-group-item">
              Дата публикации: <br>
                {{ post.created|date:"d E Y" }}
            </li>

            {% if post.group %}
              <li class="list-group-item">
                Группа: {{post.group.slug}}<br>
                <a href="{% url 'posts:group_list' post.group.slug %}" class="posts__data">Все записи группы</a>
              </li>
            {% endif %}
            <li class="list-group-item">
              Автор: <a href="{% url 'posts:profile' post.author %}" class="posts_author"> {{ post.author.get_full_name }} <br>
                <span>@aka</span> {{post.author}}</a>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: <span >{{ post_amount }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author  %}">
                Все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9 info__content">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="list-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
          <p  class="posts__text">
            {{ post.text|linebreaksbr }}
          </p>
          {% if post.author == user %}
            <div class="post__link">
              <a href="{% url 'posts:edit' post.id %}" class="posts__data"> Pедактировать пост</a>
            </div>
          {% endif %}
        </article>
      </div>
    </section>
      {% if user.is_authenticated %}
          <section id="form__comment">
              <div class="comment__card">
                <h5 class="card-header">Добавить комментарий:</h5>
                <div class="card-wrapper">
                  <form method="post" action="{% url 'posts:add_comment' post.id %}" class="form-post">
                    {% csrf_token %}
                    <div class="form-group">
                      {{ form.text }}
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                  </form>
                </div>
              </div>
          </section>
      {% endif %}
            {% if comments %}
                <h2 class="comment_header">Вот такие комментарии оставили пользователи под постом </h2>
                {% for comment in comments %}
                    <section id="comment">
                          <div class="posts_container">
                              <ul class="posts__data posts__ul">
                                <li>
                                  Автор: <a href="{% url 'posts:profile' comment.author_comment %}">{{ comment.author.get_full_name }} @aka {{comment.author_comment}}</a>
                                </li>
                                <li class="posts__li">
                                  <span class="post_article">Дата публикации:</span> {{ comment.created|date:"d E Y" }}
                                </li>
                              </ul>
                           <p class="posts__text">{{ comment.text|linebreaksbr }}</p>
                          </div>
                    </section>
                {% endfor %}
                {% else %}
                    <h2 class="comment_header"> Комментариев  пока нет. {% if user.is_authenticated %} Станьте первым {% endif %} </h2>
            {% endif %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %} Посты {{ author.first_name }} {{ author.last_name }} | Yatube {% endblock %}
    {% block content %}
    <section id="posts">
        <h1 class="main__header">Все посты пользователя: {{ author.get_full_name }} @aka {{author.username}} </h1>
        {% if author != request.user %}
            {% if following %}
                <a
                  class="btn btn-lg btn-light  follow_btn follow_btn-disable"
                  href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
                  -Отписаться
                </a>
              {% else %}
                  <a
                    class="btn btn-lg btn-primary follow_btn"
                    href="{% url 'posts:profile_follow' author.username %}" role="button"
                  >
                    +Подписаться
                  </a>
            {% endif %}
        {% endif %}

      <div class="posts container py-5">      
      {% for post in page_obj %}
        <div class="posts_container">
          {% include 'includes/description.html' %} 
          {% if post.group %}
              <div class="post__description">
                  <div class="post__link">
                    <a href="{% url 'posts:group_list' post.group.slug %}" class="posts__data">все записи группы: {{post.group.slug}}</a>
                  </div>
              </div>
          {% endif %} 
        </div> 
      {% if forloop.last %}
        
      {% endif %}
  {% endfor %} 
{% endblock %} 